name: Sync Docs to Wiki

on:
  push:
    branches:
      - main
    paths:
      - 'doc/**' # Solo se dispara si cambias algo en la carpeta doc

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Sync to Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        env:
          WIKI_DIR: doc/ # Tu carpeta origen
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
